// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Metrics.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Metrics;
    using Lykke.Service.Metrics.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetLogResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetLogResponse class.
        /// </summary>
        public GetLogResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetLogResponse class.
        /// </summary>
        public GetLogResponse(IList<LogEntry> entries = default(IList<LogEntry>))
        {
            Entries = entries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entries")]
        public IList<LogEntry> Entries { get; set; }

    }
}
