// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Metrics.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Metrics;
    using Lykke.Service.Metrics.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LogEntry
    {
        /// <summary>
        /// Initializes a new instance of the LogEntry class.
        /// </summary>
        public LogEntry()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LogEntry class.
        /// </summary>
        public LogEntry(System.DateTime moment, IList<KeyValueModel> keyValues = default(IList<KeyValueModel>))
        {
            Moment = moment;
            KeyValues = keyValues;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Moment")]
        public System.DateTime Moment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KeyValues")]
        public IList<KeyValueModel> KeyValues { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (KeyValues != null)
            {
                foreach (var element in KeyValues)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
